# Generated by Django 3.2.10 on 2021-12-31 15:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ft_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ft_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ft_created_at', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ft_id', models.PositiveIntegerField(default=0, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ft_created_at', models.DateTimeField(default='')),
                ('ft_updated_at', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ft_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('location', models.CharField(default='', max_length=100)),
                ('kind', models.CharField(default='', max_length=100)),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('nbr_subscribers', models.IntegerField(default=0)),
                ('begin_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ft_created_at', models.DateTimeField(default='')),
                ('ft_updated_at', models.DateTimeField(default='')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.campus')),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.cursus')),
                ('theme', models.ManyToManyField(related_name='events', to='core.Theme')),
            ],
        ),
    ]
