# Generated by Django 3.2.10 on 2021-12-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursus',
            name='ft_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='event',
            name='campus',
        ),
        migrations.AddField(
            model_name='event',
            name='campus',
            field=models.ManyToManyField(related_name='events', to='core.Campus'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='cursus',
        ),
        migrations.AddField(
            model_name='event',
            name='cursus',
            field=models.ManyToManyField(related_name='events', to='core.Cursus'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ft_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ft_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='ft_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='ft_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
