# Generated by Django 3.2.10 on 2022-01-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220101_0157'),
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='campus',
        ),
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.ManyToManyField(blank=True, related_name='user', to='core.Campus'),
        ),
    ]
